version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:18.04

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Auth with github
          command: |
            bash .circleci/auth_with_github.sh
      - run:
          name: Install deps
          command: |
            sudo -E bash maintenance/install_deps.sh
      - run:
          name: Install salt
          command: |
            sudo -E bash maintenance/install_salt_open.sh
      - run:
          name: Run salt
          command: |
            sudo -E bash maintenance/run_salt.sh
      - run:
          name: Run tests
          command: |
            sudo -E bash maintenance/test.sh
